### ISSUE TITLE
AdvancedCircuitBreakerSyntaxAsync.AdvancedCircuitBreakerAsync(PolicyBuilder, double, TimeSpan, int, TimeSpan, Action<Exception, TimeSpan>, Action)' requires a receiver of type 'PolicyBuilder'

### ISSUE THREAD

**Issue by jvelezc** [App-vNext/Polly.Extensions.Http#24] opened 2018-05-09 01:05 UTC
I basically wanted to add logging of exceptions on error but no matter what I try I can't get the syntax right. 

 Doesn't work:
```
Action<Exception, TimeSpan> onBreak = (exception,duration) => { };
Action onReset = () => { };
            var circuitBreaker = HttpPolicyExtensions
            .HandleTransientHttpError().AdvancedCircuitBreakerAsync
            (
                failureThreshold: 0.5,
                samplingDuration: TimeSpan.FromSeconds(10),
                minimumThroughput: 2,
                durationOfBreak: TimeSpan.FromSeconds(30),
                onBreak: onBreak,
                onReset: onReset
            );  
```

Works

```
var circuitBreaker = HttpPolicyExtensions
            .HandleTransientHttpError().AdvancedCircuitBreakerAsync
            (
                failureThreshold: 0.5,
                samplingDuration: TimeSpan.FromSeconds(10),
                minimumThroughput: 2,
                durationOfBreak: TimeSpan.FromSeconds(30)
       
            );

```

**Comment by reisenberger** [comment] 2018-05-09 07:54
Hi @jvelezc !  

Policies defined by `HttpPolicyExtensions.HandleTransientHttpError()` handle [both exceptions and Http result codes](https://github.com/App-vNext/Polly.Extensions.Http#convenience-methods-for-transient-faults-of-httpclient-calls),  This means the [first input parameter to `onBreak`](https://github.com/App-vNext/Polly/blob/27e1a83bbdd3542902f654fec1e474d01f15d815/src/Polly.Shared/CircuitBreaker/AdvancedCircuitBreakerTResultSyntaxAsync.cs#L78) is of type [`DelegateResult<HttpResponseMessage>`](https://github.com/App-vNext/Polly/blob/27e1a83bbdd3542902f654fec1e474d01f15d815/src/Polly.Shared/DelegateResult.cs) rather than `Exception`.  So:

    Action<DelegateResult<HttpResponseMessage>, TimeSpan> onBreak = (handledFault, duration) => { };
    Action onReset = () => { };
    var circuitBreaker = HttpPolicyExtensions
        .HandleTransientHttpError().AdvancedCircuitBreakerAsync
        (
            failureThreshold: 0.5,
            samplingDuration: TimeSpan.FromSeconds(10),
            minimumThroughput: 2,
            durationOfBreak: TimeSpan.FromSeconds(30),
            onBreak: onBreak,
            onReset: onReset
        );

This allows the `onBreak` delegate to also capture the cause of the failure if it was a handled Http status code.  For instance:

    Action<DelegateResult<HttpResponseMessage>, TimeSpan> onBreak = (handledFault, duration) =>
    {
        logger.LogError($"Circuit breaking for {duration} due to {handledFault.Exception?.Message ?? handledFault.Result.StatusCode.ToString()}");
    };
    Action onReset = () => { /* etc */ };

    var circuitBreaker = HttpPolicyExtensions
        .HandleTransientHttpError().AdvancedCircuitBreakerAsync
        (
            failureThreshold: 0.5,
            samplingDuration: TimeSpan.FromSeconds(10),
            minimumThroughput: 2,
            durationOfBreak: TimeSpan.FromSeconds(30),
            onBreak: onBreak,
            onReset: onReset
        );

There is more information about `DelegateResult<TResult>` [in the Polly readme](https://github.com/App-vNext/Polly#state-change-delegates-on-policytresult-policies).

I hope that helps, but let us know if there is anything else we can help with!

**Comment by reisenberger** [comment] 2018-10-31 19:19
Closing due to lack of further response.

**Closed by reisenberger** 2018-10-31 19:19 UTC
Labels: how to
